<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Hadley Wickham, Danielle Navarro, y Thomas Lin Pedersen">
<title>6&nbsp; Mapas – ggplot2: Gráficos elegantes para análisis de datos (3e)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./networks.html" rel="next">
<link href="./statistical-summaries.html" rel="prev">
<link href="./cover.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0dd2bd5de344125cf763a379ddc3eb04.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script><meta name="google-site-verification" content="kphyQu6n4JhBUuoLZxnJpD9dbw9q5FLwqXb9AkI2fhU">
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./toolbox.html">Layers</a></li><li class="breadcrumb-item"><a href="./maps.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Mapas</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ggplot2: Gráficos elegantes para análisis de datos (3e)</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label=""><i class="bi bi-github"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://github.com/hadley/ggplot2-book/">
            Original
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://github.com/davidrsch/ggplot2b-es">
            Traducción
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Alternar modo lector">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">¡Bienvenidos!</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface-3e.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio a la tercera edición</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface-2e.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio a la segunda edición.</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./start.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Empezando</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Primeros pasos</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./toolbox.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Layers</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./individual-geoms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Geomas individuales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./collective-geoms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Geomas colectivas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistical-summaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Resúmenes estadísticos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./maps.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Mapas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Redes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./annotations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Anotaciones</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./arranging-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Organizar gráficas</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./scales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scales</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scales-position.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Escalas de posición y ejes.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scales-colour.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Escalas de colores y leyendas.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scales-other.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Otra estéticas</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./mastery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">La Gramática</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./layers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Construya una gráfica capa por capa</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scales-guides.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Escalas y guías</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./coord.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Sistemas coordinados</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./facet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Facetado</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./themes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Temas</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./extending.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Temas avanzados</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Programar con ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./internals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Internos de ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./extensions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Extendiendo ggplot2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ext-springs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Un caso de estudio</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
<li><a href="#sec-polygonmaps" id="toc-sec-polygonmaps" class="nav-link active" data-scroll-target="#sec-polygonmaps"><span class="header-section-number">6.1</span> Mapas de polígonos</a></li>
  <li>
<a href="#sec-sf" id="toc-sec-sf" class="nav-link" data-scroll-target="#sec-sf"><span class="header-section-number">6.2</span> Mapas de características simples</a>
  <ul class="collapse">
<li><a href="#mapas-en-capas" id="toc-mapas-en-capas" class="nav-link" data-scroll-target="#mapas-en-capas"><span class="header-section-number">6.2.1</span> Mapas en capas</a></li>
  <li><a href="#sec-geom_sf_label" id="toc-sec-geom_sf_label" class="nav-link" data-scroll-target="#sec-geom_sf_label"><span class="header-section-number">6.2.2</span> Mapas etiquetados</a></li>
  <li><a href="#agregar-otras-geomas" id="toc-agregar-otras-geomas" class="nav-link" data-scroll-target="#agregar-otras-geomas"><span class="header-section-number">6.2.3</span> Agregar otras geomas</a></li>
  </ul>
</li>
  <li><a href="#sec-mapproj" id="toc-sec-mapproj" class="nav-link" data-scroll-target="#sec-mapproj"><span class="header-section-number">6.3</span> Proyecciones de mapas</a></li>
  <li><a href="#sec-sfdetail" id="toc-sec-sfdetail" class="nav-link" data-scroll-target="#sec-sfdetail"><span class="header-section-number">6.4</span> Trabajar con datos sf</a></li>
  <li><a href="#sec-rastermaps" id="toc-sec-rastermaps" class="nav-link" data-scroll-target="#sec-rastermaps"><span class="header-section-number">6.5</span> Mapas ráster</a></li>
  <li><a href="#fuentes-de-datos" id="toc-fuentes-de-datos" class="nav-link" data-scroll-target="#fuentes-de-datos"><span class="header-section-number">6.6</span> Fuentes de datos</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./toolbox.html">Layers</a></li><li class="breadcrumb-item"><a href="./maps.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Mapas</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-maps" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Mapas</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>You are reading the work-in-progress third edition of the ggplot2 book. This chapter should be readable but is currently undergoing final polishing.</p>
</div>
</div>
</div>
<p>Trazar datos geoespaciales es una tarea de visualización común y que requiere herramientas especializadas. Normalmente, el problema se puede descomponer en dos problemas: utilizar una fuente de datos para dibujar un mapa y agregar metadatos de otra fuente de información al mapa. Este capítulo le ayudará a abordar ambos problemas. Hemos estructurado el capítulo de la siguiente manera: <a href="#sec-polygonmaps" class="quarto-xref"><span>Sección 6.1</span></a> describe una forma sencilla de dibujar mapas usando <code>geom_polygon()</code>, seguida en <a href="#sec-sf" class="quarto-xref"><span>Sección 6.2</span></a> por un enfoque moderno de “características simples” (sf) usando <code>geom_sf()</code>. A continuación, <a href="#sec-mapproj" class="quarto-xref"><span>Sección 6.3</span></a> y <a href="#sec-sfdetail" class="quarto-xref"><span>Sección 6.4</span></a> analizan cómo trabajar con proyecciones de mapas y la estructura de datos sf subyacente. Finalmente, <a href="#sec-rastermaps" class="quarto-xref"><span>Sección 6.5</span></a> analiza cómo dibujar mapas basados en datos ráster.</p>
<section id="sec-polygonmaps" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="sec-polygonmaps">
<span class="header-section-number">6.1</span> Mapas de polígonos</h2>
<p> </p>
<p>Quizás el método más sencillo para dibujar mapas sea utilizar <code>geom_polygon()</code> para dibujar límites para diferentes regiones. Para este ejemplo tomamos datos del paquete de mapas usando <code><a href="https://ggplot2.tidyverse.org/reference/map_data.html">ggplot2::map_data()</a></code>. El paquete de mapas no es particularmente preciso ni está actualizado, pero está integrado en R, por lo que es un lugar fácil para comenzar. Aquí hay un conjunto de datos que especifica los límites del condado de Michigan:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mi_counties</span> <span class="op">&lt;-</span> <span class="fu">map_data</span><span class="op">(</span><span class="st">"county"</span>, <span class="st">"michigan"</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">select</span><span class="op">(</span>lon <span class="op">=</span> <span class="va">long</span>, <span class="va">lat</span>, <span class="va">group</span>, id <span class="op">=</span> <span class="va">subregion</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">mi_counties</span><span class="op">)</span></span>
<span><span class="co">#&gt;     lon  lat group     id</span></span>
<span><span class="co">#&gt; 1 -83.9 44.9     1 alcona</span></span>
<span><span class="co">#&gt; 2 -83.4 44.9     1 alcona</span></span>
<span><span class="co">#&gt; 3 -83.4 44.9     1 alcona</span></span>
<span><span class="co">#&gt; 4 -83.3 44.8     1 alcona</span></span>
<span><span class="co">#&gt; 5 -83.3 44.8     1 alcona</span></span>
<span><span class="co">#&gt; 6 -83.3 44.8     1 alcona</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>En este conjunto de datos tenemos cuatro variables: <code>lat</code> y <code>long</code> especifican la latitud y longitud de un vértice (es decir, una esquina del polígono), <code>id</code> especifica el nombre de una región y <code>group</code> proporciona un valor único. identificador de áreas contiguas dentro de una región (por ejemplo, si una región constaba de varias islas). Para tener una mejor idea de lo que contienen los datos, podemos trazar <code>mi_counties</code> usando <code>geom_point()</code>, como se muestra en el panel izquierdo a continuación. En este gráfico, cada fila del marco de datos se traza como un único punto, lo que produce un diagrama de dispersión que muestra las esquinas de cada condado. Para convertir este diagrama de dispersión en un mapa, usamos <code>geom_polygon()</code>, que dibuja cada condado como un polígono distinto. Esto se ilustra en el panel derecho a continuación.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">mi_counties</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">lon</span>, <span class="va">lat</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">.25</span>, show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_quickmap</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">mi_counties</span>, <span class="fu">aes</span><span class="op">(</span><span class="va">lon</span>, <span class="va">lat</span>, group <span class="op">=</span> <span class="va">group</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_polygon</span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"white"</span>, colour <span class="op">=</span> <span class="st">"grey50"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_quickmap</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="maps_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="1200"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="maps_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="1200"></p>
</div>
</div>
</div>
<p>En ambos gráficos usamos <code>coord_quickmap()</code> para ajustar los ejes y garantizar que la longitud y la latitud se representen en la misma escala. <a href="coord.html" class="quarto-xref"><span>Capítulo 15</span></a> analiza los sistemas de coordenadas en ggplot2 en términos más generales, pero como veremos a continuación, los datos geoespaciales a menudo requieren un enfoque más exigente. Por esta razón, ggplot2 proporciona <code>geom_sf()</code> y <code>coord_sf()</code> para manejar datos espaciales especificados en formato de características simples.</p>
</section><section id="sec-sf" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="sec-sf">
<span class="header-section-number">6.2</span> Mapas de características simples</h2>
<p>El enfoque descrito anteriormente tiene algunas limitaciones, entre las que destaca el hecho de que el formato de datos simple “longitud-latitud” no se utiliza normalmente en la cartografía del mundo real. Los datos vectoriales para mapas normalmente se codifican utilizando el estándar de “características simples” producido por el Open Geospatial Consortium. El paquete sf <span class="citation" data-cites="sf">(<a href="#ref-sf" role="doc-biblioref">Pebesma 2018</a>)</span> desarrollado por Edzer Pebesma <a href="https://github.com/r-spatial/sf" class="uri">https://github.com/r-spatial/sf</a> proporciona un excelente conjunto de herramientas para trabajar con dichos datos y las funciones <code>geom_sf()</code> y <code>coord_sf()</code> en ggplot2 están diseñados para funcionar junto con el paquete sf.</p>
<p>Para presentar estas funciones, nos basamos en el paquete ozmaps de Michael Sumner <a href="https://github.com/mdsumner/ozmaps/" class="uri">https://github.com/mdsumner/ozmaps/</a> que proporciona mapas de las fronteras estatales de Australia, áreas de gobierno local, límites electorales, etc. <span class="citation" data-cites="ozmaps">(<a href="#ref-ozmaps" role="doc-biblioref">Sumner 2019</a>)</span> . Para ilustrar cómo se ve un conjunto de datos sf, importamos un conjunto de datos que representa las fronteras de los estados y territorios australianos:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/mdsumner/ozmaps">ozmaps</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span></span>
<span><span class="co">#&gt; Linking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.4.0; sf_use_s2() is TRUE</span></span>
<span></span>
<span><span class="va">oz_states</span> <span class="op">&lt;-</span> <span class="fu">ozmaps</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/ozmaps/man/ozmap_states.html">ozmap_states</a></span></span>
<span><span class="va">oz_states</span></span>
<span><span class="co">#&gt; Simple feature collection with 9 features and 1 field</span></span>
<span><span class="co">#&gt; Geometry type: MULTIPOLYGON</span></span>
<span><span class="co">#&gt; Dimension:     XY</span></span>
<span><span class="co">#&gt; Bounding box:  xmin: 106 ymin: -43.6 xmax: 168 ymax: -9.23</span></span>
<span><span class="co">#&gt; Geodetic CRS:  GDA94</span></span>
<span><span class="co">#&gt; # A tibble: 9 × 2</span></span>
<span><span class="co">#&gt;   NAME                                                                  geometry</span></span>
<span><span class="co">#&gt; * &lt;chr&gt;                                                       &lt;MULTIPOLYGON [°]&gt;</span></span>
<span><span class="co">#&gt; 1 New South Wales   (((151 -35.1, 151 -35.1, 151 -35.1, 151 -35.1, 151 -35.2, 1…</span></span>
<span><span class="co">#&gt; 2 Victoria          (((147 -38.7, 147 -38.7, 147 -38.7, 147 -38.7, 147 -38.7)),…</span></span>
<span><span class="co">#&gt; 3 Queensland        (((149 -20.3, 149 -20.4, 149 -20.4, 149 -20.3)), ((149 -20.…</span></span>
<span><span class="co">#&gt; 4 South Australia   (((137 -34.5, 137 -34.5, 137 -34.5, 137 -34.5, 137 -34.5, 1…</span></span>
<span><span class="co">#&gt; 5 Western Australia (((126 -14, 126 -14, 126 -14, 126 -14, 126 -14)), ((124 -16…</span></span>
<span><span class="co">#&gt; 6 Tasmania          (((148 -40.3, 148 -40.3, 148 -40.3, 148 -40.3)), ((147 -39.…</span></span>
<span><span class="co">#&gt; # ℹ 3 more rows</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Este resultado muestra algunos de los metadatos asociados con los datos (que se analizan momentáneamente) y nos dice que los datos son esencialmente un tibble con 9 filas y 2 columnas. Una ventaja de los datos de ciencia ficción es inmediatamente evidente: podemos ver fácilmente la estructura general de los datos: Australia se compone de seis estados y algunos territorios. Hay 9 unidades geográficas distintas, por lo que hay 9 filas en este tibble (cf.&nbsp;<code>mi_counties data</code> donde hay una fila por vértice del polígono).</p>
<p>La columna más importante es “geometría” <code>geometry</code>, que especifica la geometría espacial para cada uno de los estados y territorios. Cada elemento de la columna <code>geometry</code> es un objeto multipolígono que, como su nombre indica, contiene datos que especifican los vértices de uno o más polígonos que delimitan el borde de una región. Dados los datos en este formato, podemos usar <code>geom_sf()</code> y <code>coord_sf()</code> para dibujar un mapa útil sin especificar ningún parámetro o incluso declarar explícitamente ninguna estética:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">oz_states</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_sf</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Para entender por qué esto funciona, tenga en cuenta que <code>geom_sf()</code> se basa en una estética de <code>geometry</code> que no se utiliza en ninguna otra parte de ggplot2. Esta estética se puede especificar de una de tres maneras:</p>
<ul>
<li><p>En el caso más simple (ilustrado arriba) cuando el usuario no hace nada, <code>geom_sf()</code> intentará asignarlo a una columna llamada <code>geometry</code>.</p></li>
<li><p>Si el argumento <code>data</code> es un objeto sf entonces <code>geom_sf()</code> puede detectar automáticamente una columna de geometría, incluso si no se llama <code>geometry</code>.</p></li>
<li><p>Puede especificar el mapeo manualmente de la forma habitual con <code>aes(geometry = my_column)</code>. Esto es útil si tiene varias columnas de geometría.</p></li>
</ul>
<p>La función <code>coord_sf()</code> gobierna la proyección del mapa, discutida en <a href="#sec-mapproj" class="quarto-xref"><span>Sección 6.3</span></a>.</p>
<section id="mapas-en-capas" class="level3" data-number="6.2.1"><h3 data-number="6.2.1" class="anchored" data-anchor-id="mapas-en-capas">
<span class="header-section-number">6.2.1</span> Mapas en capas</h3>
<p>En algunos casos, es posible que desees superponer un mapa encima de otro. El paquete ggplot2 admite esto permitiéndole agregar múltiples capas <code>geom_sf()</code> a un gráfico. Como ejemplo, usaremos los datos de “oz_states” para dibujar los estados australianos en diferentes colores y superpondremos este gráfico con los límites de las regiones electorales australianas. Para hacer esto, hay que realizar dos pasos de preprocesamiento. Primero, usaremos <code><a href="https://dplyr.tidyverse.org/reference/filter.html">dplyr::filter()</a></code> para eliminar los “Other Territories” de las fronteras estatales.</p>
<p>El siguiente código dibuja un gráfico con dos capas de mapa: la primera usa <code>oz_states</code> para llenar los estados en diferentes colores, y la segunda usa <code>oz_votes</code> para dibujar los límites electorales. En segundo lugar, extraeremos los límites electorales de forma simplificada utilizando la función <code>ms_simplify()</code> del paquete rmapshaper <span class="citation" data-cites="rmapshaper">(<a href="#ref-rmapshaper" role="doc-biblioref">Teucher y Russell 2018</a>)</span>. Generalmente, esto es una buena idea si el conjunto de datos original (en este caso, <code><a href="https://rdrr.io/pkg/ozmaps/man/abs-data.html">ozmaps::abs_ced</a></code>) se almacena a una resolución más alta que la que requiere su gráfico, para reducir el tiempo necesario para renderizar el gráfico.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">oz_states</span> <span class="op">&lt;-</span> <span class="fu">ozmaps</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/ozmaps/man/ozmap_states.html">ozmap_states</a></span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">NAME</span> <span class="op">!=</span> <span class="st">"Other Territories"</span><span class="op">)</span></span>
<span><span class="va">oz_votes</span> <span class="op">&lt;-</span> <span class="fu">rmapshaper</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/rmapshaper/man/ms_simplify.html">ms_simplify</a></span><span class="op">(</span><span class="fu">ozmaps</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/ozmaps/man/abs-data.html">abs_ced</a></span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Ahora que tenemos los conjuntos de datos <code>oz_states</code> y <code>oz_votes</code> para representar las fronteras estatales y electorales respectivamente, el gráfico deseado se puede construir agregando dos capas <code>geom_sf()</code> al gráfico:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">oz_states</span>, mapping <span class="op">=</span> <span class="fu">aes</span><span class="op">(</span>fill <span class="op">=</span> <span class="va">NAME</span><span class="op">)</span>, show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">oz_votes</span>, fill <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_sf</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Vale la pena señalar que la primera capa de este gráfico asigna la estética del <code>fill</code> a una variable de los datos. En este caso, la variable <code>NAME</code> es una variable categórica y no transmite ninguna información adicional, pero se puede utilizar el mismo enfoque para visualizar otros tipos de metadatos de área. Por ejemplo, si <code>oz_states</code> tuviera una columna adicional que especificara el nivel de desempleo en cada estado, podríamos asignar la estética del <code>fill</code> a esa variable.</p>
</section><section id="sec-geom_sf_label" class="level3" data-number="6.2.2"><h3 data-number="6.2.2" class="anchored" data-anchor-id="sec-geom_sf_label">
<span class="header-section-number">6.2.2</span> Mapas etiquetados</h3>
<p>Agregar etiquetas a mapas es un ejemplo de anotar gráficos (<a href="annotations.html" class="quarto-xref"><span>Capítulo 8</span></a>) y es compatible con <code>geom_sf_label()</code> y <code>geom_sf_text()</code>. Por ejemplo, si bien es razonable esperar que una audiencia australiana conozca los nombres de los estados australianos (y no están etiquetados en el gráfico anterior), pocos australianos conocerían los nombres de los diferentes electorados en la región metropolitana de Sydney. Entonces, para dibujar un mapa electoral de Sydney, primero necesitaríamos extraer los datos del mapa para los electorados relevantes y luego agregar la etiqueta. El siguiente gráfico se acerca a la región de Sydney especificando <code>xlim</code> y <code>ylim</code> en <code>coord_sf()</code> y luego usa <code>geom_sf_label()</code> para superponer cada electorado con una etiqueta:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Filtrar electorados en la región metropolitana de Sydney</span></span>
<span><span class="va">sydney_map</span> <span class="op">&lt;-</span> <span class="fu">ozmaps</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/ozmaps/man/abs-data.html">abs_ced</a></span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">NAME</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>  <span class="st">"Sydney"</span>, <span class="st">"Wentworth"</span>, <span class="st">"Warringah"</span>, <span class="st">"Kingsford Smith"</span>, <span class="st">"Grayndler"</span>, <span class="st">"Lowe"</span>, </span>
<span>  <span class="st">"North Sydney"</span>, <span class="st">"Barton"</span>, <span class="st">"Bradfield"</span>, <span class="st">"Banks"</span>, <span class="st">"Blaxland"</span>, <span class="st">"Reid"</span>, </span>
<span>  <span class="st">"Watson"</span>, <span class="st">"Fowler"</span>, <span class="st">"Werriwa"</span>, <span class="st">"Prospect"</span>, <span class="st">"Parramatta"</span>, <span class="st">"Bennelong"</span>, </span>
<span>  <span class="st">"Mackellar"</span>, <span class="st">"Greenway"</span>, <span class="st">"Mitchell"</span>, <span class="st">"Chifley"</span>, <span class="st">"McMahon"</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Dibuja el mapa electoral de Sydney</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">sydney_map</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>fill <span class="op">=</span> <span class="va">NAME</span><span class="op">)</span>, show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_sf</span><span class="op">(</span>xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">150.97</span>, <span class="fl">151.3</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">33.98</span>, <span class="op">-</span><span class="fl">33.79</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf_label</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>label <span class="op">=</span> <span class="va">NAME</span><span class="op">)</span>, label.padding <span class="op">=</span> <span class="fu">unit</span><span class="op">(</span><span class="fl">1</span>, <span class="st">"mm"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Warning in st_point_on_surface.sfc(sf::st_zm(x)): st_point_on_surface may not</span></span>
<span><span class="co">#&gt; give correct results for longitude/latitude data</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Vale la pena señalar el mensaje de advertencia. Internamente, <code>geom_sf_label()</code> usa la función <code><a href="https://r-spatial.github.io/sf/reference/geos_unary.html">st_point_on_surface()</a></code> del paquete sf para colocar etiquetas, y el mensaje de advertencia aparece porque la mayoría de los algoritmos utilizados por sf para calcular cantidades geométricas (por ejemplo, centroides, puntos interiores) se basan en una suposición. que los puntos se encuentran sobre una superficie plana bidimensional y parametrizados con coordenadas cartesianas. Esta suposición no está estrictamente justificada y, en algunos casos (por ejemplo, regiones cercanas a los polos), los cálculos que tratan la longitud y la latitud de esta manera darán respuestas erróneas. Por este motivo, el paquete sf genera mensajes de advertencia cuando se basa en esta aproximación.</p>
<!-- HW: worth commenting on warning? "st_point_on_surface may not give correct results for longitude/latitude data" -->
</section><section id="agregar-otras-geomas" class="level3" data-number="6.2.3"><h3 data-number="6.2.3" class="anchored" data-anchor-id="agregar-otras-geomas">
<span class="header-section-number">6.2.3</span> Agregar otras geomas</h3>
<p>Aunque <code>geom_sf()</code> es especial en algunos aspectos, se comporta de la misma manera que cualquier otra geom, lo que permite trazar datos adicionales en un mapa con geoms estándar. Por ejemplo, es posible que deseemos trazar las ubicaciones de las capitales australianas en el mapa usando <code>geom_point()</code>. El siguiente código ilustra cómo se hace esto:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">oz_capitals</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="fu">::</span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span> </span>
<span>  <span class="op">~</span><span class="va">city</span>,           <span class="op">~</span><span class="va">lat</span>,     <span class="op">~</span><span class="va">lon</span>,</span>
<span>  <span class="st">"Sydney"</span>,    <span class="op">-</span><span class="fl">33.8688</span>, <span class="fl">151.2093</span>,  </span>
<span>  <span class="st">"Melbourne"</span>, <span class="op">-</span><span class="fl">37.8136</span>, <span class="fl">144.9631</span>, </span>
<span>  <span class="st">"Brisbane"</span>,  <span class="op">-</span><span class="fl">27.4698</span>, <span class="fl">153.0251</span>, </span>
<span>  <span class="st">"Adelaide"</span>,  <span class="op">-</span><span class="fl">34.9285</span>, <span class="fl">138.6007</span>, </span>
<span>  <span class="st">"Perth"</span>,     <span class="op">-</span><span class="fl">31.9505</span>, <span class="fl">115.8605</span>, </span>
<span>  <span class="st">"Hobart"</span>,    <span class="op">-</span><span class="fl">42.8821</span>, <span class="fl">147.3272</span>, </span>
<span>  <span class="st">"Canberra"</span>,  <span class="op">-</span><span class="fl">35.2809</span>, <span class="fl">149.1300</span>, </span>
<span>  <span class="st">"Darwin"</span>,    <span class="op">-</span><span class="fl">12.4634</span>, <span class="fl">130.8456</span>, </span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">oz_votes</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">oz_states</span>, colour <span class="op">=</span> <span class="st">"black"</span>, fill <span class="op">=</span> <span class="cn">NA</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>data <span class="op">=</span> <span class="va">oz_capitals</span>, mapping <span class="op">=</span> <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">lon</span>, y <span class="op">=</span> <span class="va">lat</span><span class="op">)</span>, colour <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_sf</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>En este ejemplo, <code>geom_point</code> se usa solo para especificar las ubicaciones de las ciudades capitales, pero la idea básica se puede ampliar para manejar metadatos de puntos de manera más general. Por ejemplo, si los datos de oz_capitals incluyeran una variable adicional que especificara el número de electorados dentro de cada área metropolitana, podríamos codificar esos datos utilizando la estética <code>size</code>.</p>
</section></section><section id="sec-mapproj" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="sec-mapproj">
<span class="header-section-number">6.3</span> Proyecciones de mapas</h2>
<p>Al comienzo del capítulo dibujamos mapas trazando la longitud y la latitud en un plano cartesiano, como si los datos geoespaciales no fueran diferentes de otros tipos de datos que uno podría querer trazar. En una primera aproximación, esto está bien, pero no es lo suficientemente bueno si lo que importa es la precisión. Hay dos problemas fundamentales con este enfoque.</p>
<p>La primera cuestión es la forma del planeta. La Tierra no es un plano ni una esfera perfecta. Como consecuencia, para asignar un valor de coordenadas (longitud y latitud) a una ubicación necesitamos hacer suposiciones sobre todo tipo de cosas. ¿Qué tan elipsoidal es la Tierra? ¿Dónde está el centro del planeta? ¿Dónde está el punto de origen de la longitud y la latitud? ¿Dónde está el nivel del mar? ¿Cómo se mueven las placas tectónicas? Todas estas cosas son relevantes y, dependiendo de las suposiciones que se hagan, la misma coordenada se puede asignar a ubicaciones que están a muchos metros de distancia. El conjunto de suposiciones sobre la forma de la Tierra se conoce como <strong>dato geodésico</strong> y, si bien puede no ser importante para algunas visualizaciones de datos, para otras es fundamental. Hay varias opciones diferentes que uno podría considerar: si su enfoque es América del Norte, el “Datum de América del Norte” (NAD83) es una buena opción, mientras que si su perspectiva es global, el “Sistema Geodésico Mundial” (WGS84) probablemente sea mejor.</p>
<p>La segunda cuestión es la forma de su mapa. La Tierra es aproximadamente elipsoidal, pero en la mayoría de los casos los datos espaciales deben dibujarse en un plano bidimensional. No es posible mapear la superficie de un elipsoide en un plano sin cierta distorsión o corte, y tendrás que elegir qué distorsiones estás dispuesto a aceptar al dibujar un mapa. Este es el trabajo de la <strong>proyección cartográfica</strong>.</p>
<p>Las proyecciones cartográficas a menudo se clasifican en términos de las propiedades geométricas que conservan, p.</p>
<ul>
<li><p>Las proyecciones que preservan el área garantizan que las regiones de igual área en el mundo se dibujen con igual área en el mapa.</p></li>
<li><p>Las proyecciones que preservan la forma (o conformes) garantizan que se conserve la forma local de las regiones.</p></li>
</ul>
<p>Y desafortunadamente, no es posible que ninguna proyección conserve la forma y el área. Esto hace que esté un poco más allá del alcance de este libro discutir las proyecciones cartográficas en detalle, aparte de señalar que la especificación de características simples le permite indicar qué proyección cartográfica desea utilizar. Para obtener más información sobre proyecciones de mapas, consulte Geocómputo con R <a href="https://geocompr.robinlovelace.net/" class="uri">https://geocompr.robinlovelace.net/</a> <span class="citation" data-cites="lovelace_geocomputation_2019">(<a href="#ref-lovelace_geocomputation_2019" role="doc-biblioref">Lovelace, Nowosad, y Muenchow 2019</a>)</span>.</p>
<p>En conjunto, el datum geodésico (p.&nbsp;ej., WGS84), el tipo de proyección cartográfica (p.&nbsp;ej., Mercator) y los parámetros de la proyección (p.&nbsp;ej., ubicación del origen) especifican un <strong>sistema de referencia de coordenadas</strong>, o CRS, un conjunto completo de suposiciones utilizadas para traducir la información de latitud y longitud en un mapa bidimensional. Un objeto sf a menudo incluye un CRS predeterminado, como se ilustra a continuación:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="va">oz_votes</span><span class="op">)</span></span>
<span><span class="co">#&gt; Coordinate Reference System:</span></span>
<span><span class="co">#&gt;   User input: EPSG:4283 </span></span>
<span><span class="co">#&gt;   wkt:</span></span>
<span><span class="co">#&gt; GEOGCRS["GDA94",</span></span>
<span><span class="co">#&gt;     DATUM["Geocentric Datum of Australia 1994",</span></span>
<span><span class="co">#&gt;         ELLIPSOID["GRS 1980",6378137,298.257222101,</span></span>
<span><span class="co">#&gt;             LENGTHUNIT["metre",1]]],</span></span>
<span><span class="co">#&gt;     PRIMEM["Greenwich",0,</span></span>
<span><span class="co">#&gt;         ANGLEUNIT["degree",0.0174532925199433]],</span></span>
<span><span class="co">#&gt;     CS[ellipsoidal,2],</span></span>
<span><span class="co">#&gt;         AXIS["geodetic latitude (Lat)",north,</span></span>
<span><span class="co">#&gt;             ORDER[1],</span></span>
<span><span class="co">#&gt;             ANGLEUNIT["degree",0.0174532925199433]],</span></span>
<span><span class="co">#&gt;         AXIS["geodetic longitude (Lon)",east,</span></span>
<span><span class="co">#&gt;             ORDER[2],</span></span>
<span><span class="co">#&gt;             ANGLEUNIT["degree",0.0174532925199433]],</span></span>
<span><span class="co">#&gt;     USAGE[</span></span>
<span><span class="co">#&gt;         SCOPE["Horizontal component of 3D system."],</span></span>
<span><span class="co">#&gt;         AREA["Australia including Lord Howe Island, Macquarie Islands, Ashmore and Cartier Islands, Christmas Island, Cocos (Keeling) Islands, Norfolk Island. All onshore and offshore."],</span></span>
<span><span class="co">#&gt;         BBOX[-60.56,93.41,-8.47,173.35]],</span></span>
<span><span class="co">#&gt;     ID["EPSG",4283]]</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La mayor parte de este resultado corresponde a una cadena de <strong>texto conocido</strong> (WKT) que describe sin ambigüedades el CRS. sf utiliza esta representación detallada de WKT internamente, pero hay varias formas de proporcionar información al usuario que sf comprenda. Uno de esos métodos es proporcionar entrada numérica en forma de <strong>código EPSG</strong> (consulte <a href="https://epsg.org/home.html" class="uri">https://epsg.org/home.html</a>). El CRS predeterminado en los datos <code>oz_votes</code> corresponde al código EPSG 4283: El CRS predeterminado en los datos <code>oz_votes</code> corresponde al código EPSG 4283:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="va">oz_votes</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="fl">4283</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] TRUE</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>En ggplot2, el CRS está controlado por <code>coord_sf()</code>, lo que garantiza que cada capa del gráfico utilice la misma proyección. Por defecto, <code>coord_sf()</code> usa el CRS asociado con la columna de geometría de los datos<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Dado que los datos de ciencia ficción suelen ofrecer una opción sensata de CRS, este proceso normalmente se desarrolla de forma invisible y no requiere intervención del usuario. Sin embargo, si necesita configurar el CRS usted mismo, puede especificar el parámetro <code>crs</code> pasando una entrada de usuario válida a <code><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs()</a></code>. El siguiente ejemplo ilustra cómo cambiar del CRS predeterminado al código EPSG 3112:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">oz_votes</span><span class="op">)</span> <span class="op">+</span> <span class="fu">geom_sf</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">oz_votes</span><span class="op">)</span> <span class="op">+</span> <span class="fu">geom_sf</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> <span class="fu">coord_sf</span><span class="op">(</span>crs <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="fl">3112</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="maps_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="1200"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="maps_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="1200"></p>
</div>
</div>
</div>
</section><section id="sec-sfdetail" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="sec-sfdetail">
<span class="header-section-number">6.4</span> Trabajar con datos sf</h2>
<p>Como se señaló anteriormente, los mapas creados usando <code>geom_sf()</code> y <code>coord_sf()</code> dependen en gran medida de las herramientas proporcionadas por el paquete sf y, de hecho, el paquete sf contiene muchas más herramientas útiles para manipular datos de características simples. En esta sección proporcionamos una introducción a algunas de estas herramientas; Puede encontrar una cobertura más detallada en el sitio web del paquete SF <a href="https://r-spatial.github.io/sf/" class="uri">https://r-spatial.github.io/sf/</a>.</p>
<p>Para comenzar, recuerde que una ventaja de las características simples sobre otras representaciones de datos espaciales es que las unidades geográficas pueden tener una estructura complicada. Un buen ejemplo de esto en los datos de los mapas australianos es el distrito electoral de Eden-Monaro, que se muestra a continuación:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">edenmonaro</span> <span class="op">&lt;-</span> <span class="fu">ozmaps</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/ozmaps/man/abs-data.html">abs_ced</a></span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">NAME</span> <span class="op">==</span> <span class="st">"Eden-Monaro"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p</span> <span class="op">&lt;-</span> <span class="fu">ggplot</span><span class="op">(</span><span class="va">edenmonaro</span><span class="op">)</span> <span class="op">+</span> <span class="fu">geom_sf</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">p</span> <span class="op">+</span> <span class="fu">coord_sf</span><span class="op">(</span>xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">147.75</span>, <span class="fl">150.25</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">37.5</span>, <span class="op">-</span><span class="fl">34.5</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="va">p</span> <span class="op">+</span> <span class="fu">coord_sf</span><span class="op">(</span>xlim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">150</span>, <span class="fl">150.25</span><span class="op">)</span>, ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">36.3</span>, <span class="op">-</span><span class="fl">36</span><span class="op">)</span><span class="op">)</span> </span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="maps_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="1200"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="maps_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="1200"></p>
</div>
</div>
</div>
<p>Como lo ilustra esto, Eden-Monaro se define en términos de dos polígonos distintos, uno grande en el continente australiano y una isla pequeña. Sin embargo, la gran región tiene un agujero en el medio (el agujero existe porque el Territorio de la Capital Australiana es una unidad política distinta que está totalmente contenida dentro de Eden-Monaro y, como se ilustra arriba, las fronteras electorales en Australia no cruzan las fronteras estatales). En terminología sf, este es un ejemplo de geometría <code>MULTIPOLYGON</code>. En esta sección hablaremos sobre la estructura de estos objetos y cómo trabajar con ellos.</p>
<p>Primero, usemos dplyr para tomar solo el objeto de geometría:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">edenmonaro</span> <span class="op">&lt;-</span> <span class="va">edenmonaro</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu">pull</span><span class="op">(</span><span class="va">geometry</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Se puede acceder a los metadatos del objeto edenmonaro mediante funciones auxiliares. Por ejemplo, <code><a href="https://r-spatial.github.io/sf/reference/st_geometry_type.html">st_geometry_type()</a></code> extrae el tipo de geometría (por ejemplo, <code>MULTIPOLYGON</code>), <code><a href="https://r-spatial.github.io/sf/reference/geos_query.html">st_dimension()</a></code> extrae el número de dimensiones (2 para datos XY, 3 para XYZ), <code><a href="https://r-spatial.github.io/sf/reference/st_bbox.html">st_bbox()</a></code> extrae el cuadro delimitador como un vector numérico, y <code><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs()</a></code> extrae el CRS como una lista con dos componentes, uno para el código EPSG y el otro para proj4string. Por ejemplo:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_bbox.html">st_bbox</a></span><span class="op">(</span><span class="va">edenmonaro</span><span class="op">)</span></span>
<span><span class="co">#&gt;  xmin  ymin  xmax  ymax </span></span>
<span><span class="co">#&gt; 147.7 -37.5 150.2 -34.5</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Normalmente, cuando imprimimos el objeto <code>edenmonaro</code>, la salida mostrará toda la información adicional (dimensión, cuadro delimitador, dato geodésico, etc.), pero durante el resto de esta sección mostraremos solo las líneas relevantes de la salida. En este caso, edenmonaro está definido por una geometría MULTIPOLYGON que contiene una característica:</p>
<div class="cell" data-output.lines="[-3,-4,-5,-6]">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">edenmonaro</span> </span>
<span><span class="co">#&gt; Geometry set for 1 feature </span></span>
<span><span class="co">#&gt; Geometry type: MULTIPOLYGON</span></span>
<span><span class="co">#&gt; MULTIPOLYGON (((150 -36.2, 150 -36.2, 150 -36.3...</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Sin embargo, podemos “fundir” el MULTIPOLYGON en las dos geometrías POLYGON distintas a partir de las cuales está construido usando <code><a href="https://r-spatial.github.io/sf/reference/st_cast.html">st_cast()</a></code>:</p>
<div class="cell" data-output.lines="[-3,-4,-5,-6]">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_cast.html">st_cast</a></span><span class="op">(</span><span class="va">edenmonaro</span>, <span class="st">"POLYGON"</span><span class="op">)</span></span>
<span><span class="co">#&gt; Geometry set for 2 features </span></span>
<span><span class="co">#&gt; Geometry type: POLYGON</span></span>
<span><span class="co">#&gt; POLYGON ((150 -36.2, 150 -36.2, 150 -36.3, 150 ...</span></span>
<span><span class="co">#&gt; POLYGON ((148 -36.7, 148 -36.7, 148 -36.7, 148 ...</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Para ilustrar cuándo esto podría ser útil, consideremos el electorado de Dawson, que consta de 69 islas además de una región costera en el continente australiano.</p>
<div class="cell" data-output.lines="[-3,-4,-5,-6]">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dawson</span> <span class="op">&lt;-</span> <span class="fu">ozmaps</span><span class="fu">::</span><span class="va"><a href="https://rdrr.io/pkg/ozmaps/man/abs-data.html">abs_ced</a></span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">NAME</span> <span class="op">==</span> <span class="st">"Dawson"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">pull</span><span class="op">(</span><span class="va">geometry</span><span class="op">)</span></span>
<span><span class="va">dawson</span></span>
<span><span class="co">#&gt; Geometry set for 1 feature </span></span>
<span><span class="co">#&gt; Geometry type: MULTIPOLYGON</span></span>
<span><span class="co">#&gt; MULTIPOLYGON (((148 -19.9, 148 -19.8, 148 -19.8...</span></span>
<span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">dawson</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_sf</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Supongamos, sin embargo, que nuestro interés es sólo cartografiar las islas. Si es así, primero podemos usar la función <code><a href="https://r-spatial.github.io/sf/reference/st_cast.html">st_cast()</a></code> para dividir el electorado de Dawson en los polígonos constituyentes. Después de hacerlo, podemos usar <code><a href="https://r-spatial.github.io/sf/reference/geos_measures.html">st_area()</a></code> para calcular el área de cada polígono y <code><a href="https://rdrr.io/r/base/which.min.html">which.max()</a></code> para encontrar el polígono con área máxima:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dawson</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_cast.html">st_cast</a></span><span class="op">(</span><span class="va">dawson</span>, <span class="st">"POLYGON"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/which.min.html">which.max</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/geos_measures.html">st_area</a></span><span class="op">(</span><span class="va">dawson</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 69</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La gran región continental corresponde al polígono 69 dentro de Dawson. Armados con este conocimiento, podemos dibujar un mapa que muestre solo las islas:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="va">dawson</span><span class="op">[</span><span class="op">-</span><span class="fl">69</span><span class="op">]</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_sf</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
</section><section id="sec-rastermaps" class="level2" data-number="6.5"><h2 data-number="6.5" class="anchored" data-anchor-id="sec-rastermaps">
<span class="header-section-number">6.5</span> Mapas ráster</h2>
<!-- HW: do you have any thoughts on a modern approach to this problem? -->
<p>Una segunda forma de proporcionar información geoespacial para la cartografía es confiar en <strong>datos ráster</strong>. A diferencia del formato de entidades simples, en el que las entidades geográficas se especifican en términos de un conjunto de líneas, puntos y polígonos, los rásteres toman la forma de imágenes. En el caso más simple, los datos ráster pueden no ser más que un archivo de mapa de bits, pero existen muchos formatos de imagen diferentes. Específicamente en el contexto geoespacial, existen formatos de imágenes que incluyen metadatos (por ejemplo, datos geodésicos, sistema de referencia de coordenadas) que se pueden usar para mapear la información de la imagen en la superficie de la Tierra. Por ejemplo, un formato común es GeoTIFF, que es un archivo TIFF normal con metadatos adicionales. Afortunadamente, la mayoría de los formatos se pueden leer fácilmente en R con la ayuda de GDAL (la Biblioteca de abstracción de datos geoespaciales, <a href="https://gdal.org/" class="uri">https://gdal.org/</a>). Por ejemplo, el paquete sf contiene una función <code><a href="https://r-spatial.github.io/sf/reference/gdal.html">sf::gdal_read()</a></code> que proporciona acceso a los controladores ráster GDAL desde R. Sin embargo, rara vez es necesario llamar a esta función directamente, ya que existen otras funciones de alto nivel que se encargan de esto. para ti.</p>
<p>Como ilustración, usaremos una imagen de satélite tomada por el satélite geoestacionario Himawari-8 operado por la Agencia Meteorológica de Japón y obtenida originalmente del sitio web de la Oficina Australiana de Meteorología. Esta imagen está almacenada en un archivo GeoTIFF llamado “IDE00422.202001072100.tif”.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Para importar estos datos a R, usaremos el paquete de estrellas <span class="citation" data-cites="stars">(<a href="#ref-stars" role="doc-biblioref">Pebesma 2020</a>)</span> para crear objetos de estrellas:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/stars/">stars</a></span><span class="op">)</span></span>
<span><span class="co">#&gt; Loading required package: abind</span></span>
<span><span class="va">sat_vis</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/stars/reference/read_stars.html">read_stars</a></span><span class="op">(</span></span>
<span>  <span class="st">"IDE00422.202001072100.tif"</span>, </span>
<span>  RasterIO <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>nBufXSize <span class="op">=</span> <span class="fl">600</span>, nBufYSize <span class="op">=</span> <span class="fl">600</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>En el código anterior, el primer argumento especifica la ruta al archivo ráster y el argumento <code>RasterIO</code> se usa para pasar una lista de parámetros de bajo nivel a GDAL. En este caso, hemos utilizado <code>nBufXSize</code> y <code>nBufYSize</code> para garantizar que R lea los datos en baja resolución (como una imagen de 600x600 píxeles). Para ver qué información ha importado R, podemos inspeccionar el objeto <code>sat_vis</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">sat_vis</span></span>
<span><span class="co">#&gt; stars object with 3 dimensions and 1 attribute</span></span>
<span><span class="co">#&gt; attribute(s), summary of first 1e+05 cells:</span></span>
<span><span class="co">#&gt;                            Min. 1st Qu. Median Mean 3rd Qu. Max.</span></span>
<span><span class="co">#&gt; IDE00422.202001072100.tif     0       0      0 18.1       0  255</span></span>
<span><span class="co">#&gt; dimension(s):</span></span>
<span><span class="co">#&gt;      from  to   offset  delta                  refsys point x/y</span></span>
<span><span class="co">#&gt; x       1 600 -5500000  18333 Geostationary_Satellite FALSE [x]</span></span>
<span><span class="co">#&gt; y       1 600  5500000 -18333 Geostationary_Satellite FALSE [y]</span></span>
<span><span class="co">#&gt; band    1   3       NA     NA                      NA    NA</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Este resultado nos dice algo sobre la estructura de un objeto estrella. Para el objeto <code>sat_vis</code>, los datos subyacentes se almacenan como una matriz tridimensional, con las dimensiones <code>x</code> e <code>y</code> que especifican los datos espaciales. La dimensión <code>band</code> en este caso corresponde al canal de color (RGB), pero es redundante para esta imagen ya que los datos están en escala de grises. En otros conjuntos de datos puede haber bandas correspondientes a diferentes sensores y posiblemente también una dimensión temporal. Tenga en cuenta que los datos espaciales también están asociados con un sistema de referencia de coordenadas (denominado “refsys” en el resultado).</p>
<p>Para trazar los datos <code>sat_vis</code> en ggplot2, podemos usar la función <code><a href="https://r-spatial.github.io/stars/reference/geom_stars.html">geom_stars()</a></code> proporcionada por el paquete stars. Un gráfico mínimo podría verse así:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/stars/reference/geom_stars.html">geom_stars</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">sat_vis</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_equal</span><span class="op">(</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>La función <code><a href="https://r-spatial.github.io/stars/reference/geom_stars.html">geom_stars()</a></code> requiere que el argumento <code>data</code> sea un objeto de estrellas y asigna los datos ráster a la estética de relleno. En consecuencia, el sombreado azul en la imagen de satélite de arriba está determinado por la escala ggplot2, no por la imagen en sí. Es decir, aunque <code>sat_vis</code> contiene tres bandas, el gráfico anterior solo muestra la primera, y los valores de datos sin procesar (que van de 0 a 255) se asignan a la paleta azul predeterminada que usa ggplot2 para datos continuos. Para ver cómo se ve “realmente” el archivo de imagen, podemos separar las bandas usando <code>facet_wrap()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/stars/reference/geom_stars.html">geom_stars</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">sat_vis</span>, show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">facet_wrap</span><span class="op">(</span><span class="fu">vars</span><span class="op">(</span><span class="va">band</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_equal</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">scale_fill_gradient</span><span class="op">(</span>low <span class="op">=</span> <span class="st">"black"</span>, high <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="2400"></p>
</figure>
</div>
</div>
</div>
<p>Una limitación para mostrar solo la imagen sin procesar es que no es fácil determinar dónde están las masas de tierra relevantes y es posible que deseemos superponer los datos satelitales con el mapa vectorial <code>oz_states</code> para mostrar los contornos de las entidades políticas australianas. Sin embargo, se requiere cierto cuidado al hacerlo porque las dos fuentes de datos están asociadas con diferentes sistemas de referencia de coordenadas. Para proyectar los datos <code>oz_states</code> correctamente, los datos deben transformarse usando la función <code><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform()</a></code> del paquete sf. En el código siguiente, extraemos el CRS del objeto ráster <code>sat_vis</code> y transformamos los datos <code>oz_states</code> para usar el mismo sistema.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">oz_states</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform</a></span><span class="op">(</span><span class="va">oz_states</span>, crs <span class="op">=</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="va">sat_vis</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Una vez hecho esto, ahora podemos dibujar el mapa vectorial sobre la parte superior de la imagen rasterizada para que la imagen sea más interpretable para el lector. Ahora se desprende claramente de la inspección que la imagen de satélite fue tomada durante el amanecer en Australia:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/stars/reference/geom_stars.html">geom_stars</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">sat_vis</span>, show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">oz_states</span>, fill <span class="op">=</span> <span class="cn">NA</span>, color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_sf</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_void</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">scale_fill_gradient</span><span class="op">(</span>low <span class="op">=</span> <span class="st">"black"</span>, high <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>¿Qué pasaría si quisiéramos trazar datos más convencionales en la parte superior? Un ejemplo sencillo de esto sería trazar las ubicaciones de las capitales australianas según el marco de datos <code>oz_capitals</code> que contiene datos de latitud y longitud. Sin embargo, debido a que estos datos no están asociados con un CRS y no están en la misma escala que los datos ráster en <code>sat_vis</code>, <em>también</em> deberán transformarse. Para hacerlo, primero necesitamos crear un objeto sf a partir de los datos de <code>oz_capitals</code> usando <code><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf()</a></code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cities</span> <span class="op">&lt;-</span> <span class="va">oz_capitals</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span>coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"lon"</span>, <span class="st">"lat"</span><span class="op">)</span>, crs <span class="op">=</span> <span class="fl">4326</span>, remove <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Esta proyección se establece utilizando el código EPSG 4326, una proyección elipsoidal que utiliza los valores de latitud y longitud como coordenadas y se basa en el datum WGS84. Una vez hecho esto, ahora podemos transformar las coordenadas de la geometría de latitud-longitud para que coincidan con la geometría de nuestros datos <code>sat_vis</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">cities</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform</a></span><span class="op">(</span><span class="va">cities</span>, <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="va">sat_vis</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Los datos transformados ahora se pueden superponer usando <code>geom_sf()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://r-spatial.github.io/stars/reference/geom_stars.html">geom_stars</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">sat_vis</span>, show.legend <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">oz_states</span>, fill <span class="op">=</span> <span class="cn">NA</span>, color <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">cities</span>, color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">coord_sf</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">theme_void</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">scale_fill_gradient</span><span class="op">(</span>low <span class="op">=</span> <span class="st">"black"</span>, high <span class="op">=</span> <span class="st">"white"</span><span class="op">)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="maps_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Esta versión de la imagen deja más claro que la imagen de satélite fue tomada aproximadamente al amanecer en Darwin: el sol había salido en todas las ciudades del este, pero no en Perth. Esto podría aclararse en la visualización de datos usando la función <code>geom_sf_text()</code> para agregar etiquetas a cada ciudad. Por ejemplo, podríamos agregar otra capa al gráfico usando un código como este:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">geom_sf_text</span><span class="op">(</span>data <span class="op">=</span> <span class="va">cities</span>, mapping <span class="op">=</span> <span class="fu">aes</span><span class="op">(</span>label <span class="op">=</span> <span class="va">city</span><span class="op">)</span><span class="op">)</span> </span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>aunque se requeriría algo de cuidado para asegurar que el texto esté bien colocado (ver <a href="annotations.html" class="quarto-xref"><span>Capítulo 8</span></a>).</p>
</section><section id="fuentes-de-datos" class="level2" data-number="6.6"><h2 data-number="6.6" class="anchored" data-anchor-id="fuentes-de-datos">
<span class="header-section-number">6.6</span> Fuentes de datos</h2>
<ul>
<li><p>El paquete de límites de EE.UU., <a href="https://github.com/ropensci/USAboundaries" class="uri">https://github.com/ropensci/USAboundaries</a> contiene datos de estado, condado y código postal de EE. UU. <span class="citation" data-cites="USAboundaries">(<a href="#ref-USAboundaries" role="doc-biblioref">Mullen y Bratt 2018</a>)</span>. Además de los límites actuales, también tiene límites estatales y de condado que se remontan al siglo XVII.</p></li>
<li><p>El paquete tigris, <a href="https://github.com/walkerke/tigris" class="uri">https://github.com/walkerke/tigris</a>, facilita el acceso a los archivos de forma TIGRIS del censo de EE. UU. <span class="citation" data-cites="tigris">(<a href="#ref-tigris" role="doc-biblioref">Walker 2019</a>)</span>. Contiene límites de estados, condados, códigos postales y zonas censales, así como muchos otros conjuntos de datos útiles.</p></li>
<li><p>El paquete rnaturalearth <span class="citation" data-cites="rnaturalearth">(<a href="#ref-rnaturalearth" role="doc-biblioref">South 2017</a>)</span> reúne los datos gratuitos y de alta calidad de <a href="https://naturalearthdata.com/" class="uri">https://naturalearthdata.com/</a>. Contiene las fronteras de los países y las fronteras de la región de nivel superior dentro de cada país (por ejemplo, estados de EE. UU., regiones de Francia, condados del Reino Unido).</p></li>
<li><p>El paquete osmar, <a href="https://cran.r-project.org/package=osmar" class="uri">https://cran.r-project.org/package=osmar</a> resume la API de OpenStreetMap para que pueda acceder a una amplia gama de datos vectoriales, incluidas calles y edificios individuales <span class="citation" data-cites="osmar">(<a href="#ref-osmar" role="doc-biblioref">Eugster y Schlesinger 2010</a>)</span>.</p></li>
<li><p>Si tienes tus propios archivos de formas (<code>.shp</code>) puedes cargarlos en R con <code><a href="https://r-spatial.github.io/sf/reference/st_read.html">sf::read_sf()</a></code>.</p></li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-osmar" class="csl-entry" role="listitem">
Eugster, Manuel J. A., y Thomas Schlesinger. 2010. <span>«osmar: OpenStreetMap and R»</span>. <em>R Journal</em>. <a href="http://osmar.r-forge.r-project.org/RJpreprint.pdf">http://osmar.r-forge.r-project.org/RJpreprint.pdf</a>.
</div>
<div id="ref-lovelace_geocomputation_2019" class="csl-entry" role="listitem">
Lovelace, Robin, Jakub Nowosad, y Jannes Muenchow. 2019. <em>Geocomputation with <span>R</span></em>. <span>CRC Press</span>.
</div>
<div id="ref-USAboundaries" class="csl-entry" role="listitem">
Mullen, Lincoln A., y Jordan Bratt. 2018. <span>«<span>USAboundaries</span>: Historical and Contemporary Boundaries of the United States of America»</span>. <em>Journal of Open Source Software</em> 3: 314. <a href="https://doi.org/10.21105/joss.00314">https://doi.org/10.21105/joss.00314</a>.
</div>
<div id="ref-sf" class="csl-entry" role="listitem">
Pebesma, Edzer. 2018. <span>«<span>Simple Features for R: Standardized Support for Spatial Vector Data</span>»</span>. <em><span>The R Journal</span></em> 10 (1): 439-46. <a href="https://doi.org/10.32614/RJ-2018-009">https://doi.org/10.32614/RJ-2018-009</a>.
</div>
<div id="ref-stars" class="csl-entry" role="listitem">
———. 2020. <em>stars: Spatiotemporal Arrays, Raster and Vector Data Cubes</em>.
</div>
<div id="ref-rnaturalearth" class="csl-entry" role="listitem">
South, Andy. 2017. <em>rnaturalearth: World Map Data from Natural Earth</em>. <a href="https://CRAN.R-project.org/package=rnaturalearth">https://CRAN.R-project.org/package=rnaturalearth</a>.
</div>
<div id="ref-ozmaps" class="csl-entry" role="listitem">
Sumner, Michael. 2019. <em>ozmaps: Australia Maps</em>. <a href="https://CRAN.R-project.org/package=ozmaps">https://CRAN.R-project.org/package=ozmaps</a>.
</div>
<div id="ref-rmapshaper" class="csl-entry" role="listitem">
Teucher, Andy, y Kenton Russell. 2018. <em>rmapshaper: Client for ’mapshaper’ for ’Geospatial’ Operations</em>. <a href="https://CRAN.R-project.org/package=rmapshaper">https://CRAN.R-project.org/package=rmapshaper</a>.
</div>
<div id="ref-tigris" class="csl-entry" role="listitem">
Walker, Kyle. 2019. <em>tigris: Load Census TIGER/Line Shapefiles</em>. <a href="https://CRAN.R-project.org/package=tigris">https://CRAN.R-project.org/package=tigris</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>Si hay varios conjuntos de datos con un CRS asociado diferente, utiliza el CRS de la primera capa.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Si desea probar este código usted mismo, puede encontrar una copia de la imagen en el repositorio de GitHub del libro: <a href="https://github.com/hadley/ggplot2-book/raw/master/IDE00422.202001072100.tif" class="uri">https://github.com/hadley/ggplot2-book/raw/master/IDE00422.202001072100.tif</a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script>

  // Chapter name
  const currentChapterFile = window.location.pathname.split('/').pop().replace('.html', '');

  //Defining urls
  const originalURL = "https://github.com/hadley/ggplot2-book";
  const translationURL = "https://github.com/davidrsch/ggplot2b-es";

  //Defining texts
  const edit_text = "Editar esta página";
  const issue_text = "Informar de un problema"

  //Defining git_i
  const git_i = '<div><i class="bi bi-github"></i></div>';

  // Adding TOC if not exist
  const sidebarmargin = document.getElementById('quarto-margin-sidebar');
  const buscar_TOC = document.getElementById('TOC');

  if (!buscar_TOC) {
    const crear_TOC = document.createElement('nav');
    crear_TOC.id = 'TOC';
    crear_TOC.role = "doc-toc";
    crear_TOC.class = "toc-active";
    sidebarmargin.appendChild(crear_TOC);
  }


  // Adding original github actions
  const TOC = document.getElementById('TOC');
  const originalga = document.createElement('h2');
  originalga.textContent = "Original";
  originalga.style["border-top"] = "1px solid #ccc";
  originalga.style["padding-top"] = "0.5rem";
  const toc_act_O = document.createElement('div');
  toc_act_O.className = 'toc-actions';
  toc_act_O.id = 'toc-act-O';
  const act_link_O = document.createElement('div');
  act_link_O.className='action-links';
  act_link_O.id='act-link-O';
  const edit_issue_O ='<p><a href="'+originalURL+'/edit/master/'+currentChapterFile+'.qmd" class="toc-action">'+edit_text+'</p><p><a href="'+originalURL+'/issues/new" class="toc-action">'+issue_text+'</p>';


  TOC.appendChild(originalga);
  TOC.appendChild(toc_act_O);
  toc_act_O.innerHTML += git_i;
  toc_act_O.appendChild(act_link_O);
  act_link_O.innerHTML += edit_issue_O;

  // Adding translation github actions
  const translationga = document.createElement('h2');
  translationga.textContent = "Traducción";
  const toc_act_T = document.createElement('div');
  toc_act_T.className = 'toc-actions';
  toc_act_T.id = 'toc-act-T';
  const act_link_T = document.createElement('div');
  act_link_T.className='action-links';
  act_link_T.id='act-link-T';
  const edit_issue_T ='<p><a href="'+translationURL+'/edit/main/'+currentChapterFile+'.qmd" class="toc-action">'+edit_text+'</p><p><a href="'+translationURL+'/issues/new" class="toc-action">'+issue_text+'</p>';


  TOC.appendChild(translationga);
  TOC.appendChild(toc_act_T);
  toc_act_T.innerHTML += git_i;
  toc_act_T.appendChild(act_link_T);
  act_link_T.innerHTML += edit_issue_T;


</script><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/davidrsch\.github\.io\/ggplot2b-es\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./statistical-summaries.html" class="pagination-link" aria-label="Resúmenes estadísticos">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Resúmenes estadísticos</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./networks.html" class="pagination-link" aria-label="Redes">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Redes</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>ggplot2: Gráficos elegantes para análisis de datos (3e) fue escrito por Hadley Wickham, Danielle Navarro, y Thomas Lin Pedersen.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Este libro fue creado usando <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>


</body></html>